# Generated by Django 4.0 on 2022-05-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cursos_completados',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
