# Generated by Django 4.0 on 2022-05-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='comision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
